# Generated by Django 4.2.6 on 2023-11-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_remove_funcionario_id_remove_funcionario_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celular',
            name='detalhes_celular',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='pessoa_ptr',
        ),
        migrations.AddField(
            model_name='celular',
            name='armazenamento_interno',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celular',
            name='fabricante',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celular',
            name='imagem',
            field=models.ImageField(default=1, upload_to='imagens/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celular',
            name='memoria_ram',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celular',
            name='sistema_operacional',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DetalhesCelular',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
